### ISSUE TITLE
Little question on dropping values

### ISSUE THREAD

**Issue by Kbeggen42** [Kbeggen42/wolf-depredation#5]
Hey @AaronGullickson -- I have (what I hope) is a pretty easy quick question.

I'm trying to drop states (Idaho and California) in my cattle population and cattle loss datasets, but I'm not quite there with the coding. My approach was the just select the states I want and omit the ones I want to drop. The code starts at line 31 in the organize_data file, but I'll also paste it below. I also want to rename the values so they're not yelling at me lol. 

cattle_pop <- cattle_pop |>
  filter(State) |>
  select(MONTANA, OREGON, WASHINGTON, WYOMING) |>
  rename(montana= MONTANA, oregon= OREGON, washington= WASHINGTON,
         wyoming= WYOMING)

cattle_loss <- cattle_loss |>
  filter(State) |>
  select(MONTANA, OREGON, WASHINGTON, WYOMING) |>
  rename(montana= MONTANA, oregon= OREGON, washington= WASHINGTON,
         wyoming= WYOMING)

**Comment by AaronGullickson** [comment]
The `select` command does not work like that. It is used for selecting which variables you want to keep. The state names are not variables, they are values in the `State` variable. 

`filter` does what you want but you want something like

```r
cattle_pop <- cattle_pop |>
    filter(State!="IDAHO" & State!="CALIFORNIA")
```

Another way to do this is the `%in% syntax. You can create a vector of state names you want to keep, like:

```r
keep_states <- c("MONTANA","OREGON","WASHINGTON","WYOMING")
```

Then:

```r
cattle_pop <- cattle_pop |>
    filter(State %in% keep_states)
```

Alternatively, if its easier, you can create a list of states to drop:

```r
drop_states <- c("IDAHO","CALIFORNIA")
cattle_pop <- cattle_pop |>
    filter(!(State %in% drop_states))
```

The `!` basically means keep all the states except for ones listed in this vector.
