### ISSUE TITLE
Finished Lab Notebook!

### ISSUE THREAD

**Issue by Kbeggen42** [Kbeggen42/wolf-depredation#8]
@AaronGullickson -- finished my lab notebook!! (mostly)? I think I knitted it to HTML. I got this link here: http://localhost:5138/analysis/analysis.html

I don't know why my table at the very bottom isn't as pretty as my figures 🤔

A question I do have for you: I tried to liik at the correlation coefficient between wolf population and cattle depredations and got an NA (cor(all_combo$wolf_pop, all_combo$wolf_cattle_kills). If there was no correlation I would have gotten a zero, right? 

Thanks Aaron!

**Comment by Kbeggen42** [comment]
Change:: I remembered that when coding the dependent variable has to come first when making linear models (oops!) so I fixed that issue. Then when I went to run everything my final table got mad at me! It's saying that the matrix needs a vector length of 2 and umm I'm not quite sure what that means. 

I still have that question about correlation coefficients: cor(all_combo$wolf_pop, all_combo$wolf_cattle_kills) = NA :(

**Comment by AaronGullickson** [comment]
All of your models are just predicting different DVs with year:

```r
model1 <- lm(all_combo$wolf_pop~all_combo$year)
model2 <- lm(all_combo$wolf_cattle_kills~all_combo$year)
model3 <- lm(all_combo$total_loss~all_combo$year)
```

So, when you put that into screenreg or texreg, there is only one independent variable, but you are trying to add many variables names in custom.coef.names. I think maybe you want `custom.model.names`?

```r
screenreg(list(model1,model2,model3),
      custom.model.names= c("Wolf Population", 
                           "Wolf Cattle Depredation", "Total Cattle Loss"),
      digits=3,
      caption.above=TRUE,
      include.rsquared=TRUE,
      include.adjrs=FALSE,
      include.nobs=TRUE,
      include.rmse=FALSE)
```

```
===========================================================================
                Wolf Population  Wolf Cattle Depredation  Total Cattle Loss
---------------------------------------------------------------------------
(Intercept)       2768.088       -2516.084                 -387820.455     
                (43959.690)      (2850.318)               (1487092.001)    
all_combo$year      -1.168           1.263                     211.364     
                   (21.795)         (1.413)                   (737.278)    
---------------------------------------------------------------------------
R^2                  0.000           0.022                       0.002     
Num. obs.           41              38                          44         
===========================================================================
*** p < 0.001; ** p < 0.01; * p < 0.05
```

On the cor command, you need to tell it to drop missing values:

```r
cor(all_combo$wolf_pop, all_combo$wolf_cattle_kills, use="complete.obs")
```

**Comment by Kbeggen42** [comment]
Yesss! Thank you so much @AaronGullickson. I just committed and pushed al of the changes. I'm almost done with my paper! 
new HTML link: http://localhost:5138/analysis/analysis.html

**Comment by AaronGullickson** [comment]
lol, I appreciate those html links, but they are to localhost which is on ..... your computer. No worries, though I can get my own version.

**Comment by Kbeggen42** [comment]
😂😂😂  over here I thought I was good because I tried it out on incognito mode. Even incognito mode can see right through me
